version: "3.8"

networks:
  node-api-network:
    name: node-api-network

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:2000"
    volumes:
      - .:/app
      - "/app/node_modules"
    depends_on:
      - mysql_server
    networks:
      - node-api-network

  mysql_server:
    image: mysql
    environment:
      - MYSQL_DATABASE=testing_db
      - MYSQL_PASSWORD=Mysql123
      - MYSQL_ROOT_PASSWORD=Mysql123
    networks:
      - node-api-network
